/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#263143',
        'surface-container': '#e7eeff',
        'on-primary-fixed': '#0f0069',
        'on-tertiary-container': '#ffd2be',
        primary: '#3525cd',
        outline: '#777587',
        'on-secondary-fixed-variant': '#004395',
        'status-error': '#EF4444',
        'status-neutral': '#94A3B8',
        'tertiary-fixed-dim': '#ffb695',
        'surface-bright': '#f9f9ff',
        'error-container': '#ffdad6',
        'secondary-container': '#2170e4',
        'on-tertiary': '#ffffff',
        'on-background': '#111c2d',
        error: '#ba1a1a',
        'inverse-primary': '#c3c0ff',
        'bg-subtle': '#FAFAFA',
        'surface-container-low': '#f0f3ff',
        'outline-variant': '#c7c4d8',
        'status-success': '#22C55E',
        'border-gray': '#E2E8F0',
        'on-primary': '#ffffff',
        'on-secondary-container': '#fefcff',
        secondary: '#0058be',
        surface: '#f9f9ff',
        'on-tertiary-fixed': '#351000',
        'surface-tint': '#4d44e3',
        'tertiary-container': '#a44100',
        'surface-dim': '#cfdaf2',
        'surface-container-high': '#dee8ff',
        'on-surface-variant': '#464555',
        'primary-container': '#4f46e5',
        'status-warning': '#F59E0B',
        'on-surface': '#111c2d',
        'secondary-fixed': '#d8e2ff',
        background: '#f9f9ff',
        'surface-container-highest': '#d8e3fb',
        'primary-fixed': '#e2dfff',
        'on-secondary-fixed': '#001a42',
        'on-primary-fixed-variant': '#3323cc',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#adc6ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '260px',
        'topbar-height': '64px',
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'margin-desktop': '2rem',
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter'],
        caption: ['Inter'],
        'label-md': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-sm': ['Inter'],
        'label-sm': ['Inter'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
